Repository voxpupuli/puppet-patroni, pull requests merged in 2025-02, with the labels that each got.

#54 update ensure_packages()->stdlib::ensure_packages()
  manifests/init.pp
  metadata.json
Labels: enhancement

#53 Add support for Debian 12
  .github/workflows/ci.yaml
  data/os/Debian/12.yaml
  metadata.json
  spec/acceptance/nodesets/debian-12.yml
  spec/classes/init_spec.rb
  spec/spec_helper_local.rb
Labels: enhancement

#52 Drop workaround for Puppet 5 and older
  manifests/init.pp
Labels: backwards-incompatible

#49 Add http_proxy support for pip commands
  REFERENCE.md
  manifests/init.pp
  spec/classes/init_spec.rb
Labels: enhancement

#38 Fix improper parsing of pgsql_replica_method
  manifests/init.pp
  templates/postgresql.yml.erb
Labels: enhancement

#60 modulesync: Unpin voxpupuli-test; remove faraday
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  spec/spec_helper_local.rb
Labels: modulesync

#62 Apply partial modulesync 9.4.0
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .github/workflows/ci.yaml
  Gemfile
  README.md
  Rakefile
Labels: modulesync
