Repository voxpupuli/puppet-patroni, pull requests merged in 2025-04, with the labels that each got.

#66 Add support for etcd protocol version 3
  REFERENCE.md
  manifests/init.pp
  templates/postgresql.yml.erb
Labels: enhancement

#57 modulesync 9.4.0
  .github/workflows/ci.yaml
  .github/workflows/ci.yml
  .msync.yml
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  Rakefile
  spec/acceptance/nodesets/debian-11.yml
  spec/acceptance/nodesets/debian-12.yml
  spec/acceptance/nodesets/el8.yml
  spec/acceptance/nodesets/el9.yml
  spec/acceptance/nodesets/ubuntu-2004.yml
  spec/acceptance/nodesets/ubuntu-2204.yml
  spec/acceptance/patroni_spec.rb
  spec/default_facts.yml
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_setup.rb
Labels: modulesync

#68 Add AlmaLinux/OracleLinux/CentOS support
  metadata.json
  spec/classes/init_spec.rb
  spec/support/spec/platform_data.rb
Labels: enhancement

#71 remove debug output from tests
  spec/support/spec/platform_data.rb
Labels: skip-changelog
